title: Christoph Schorn
logotitle: C.S.

fullname: Christoph Schorn
email: christoph.schorn@gmail.com

# Socials
github: chrschorn
gscholar: 0PlA9CsAAAAJ
linkedin: christoph-schorn
xing: christoph-schorn

# Variables
resumepath: /pdf/Resume_Christoph_Schorn.pdf

# Build settings
markdown: kramdown

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap