title: Christoph Schorn
logotitle: C. Schorn
fullname: Christoph Schorn

# Socials
github: chrschorn
gscholar: 0PlA9CsAAAAJ
linkedin: christoph-schorn
xing: christoph-schorn

# Variables
resumeid: 1-5PWHb1MBZzUaCOnpgNPr1vlCBSg7x2T

# Build settings
markdown: kramdown

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap