basic_settings:
  site_title: Christoph Schorn
  site_tagline: Software Engineer | Photographer | Musician
  site_subtagline:
  favicon_image: /images/favicon.png
  resume_id: 1-5PWHb1MBZzUaCOnpgNPr1vlCBSg7x2T

header_settings:
  avatar_image: /images/avatar.jpg
  logo_image: 
  logo_width: 200

menu_settings:
  menu_items:
    - title: 'Home'
      url: '/'
    - title: 'Photo'
      url: '/photo/'
    - title: 'Music'
      url: '/music/'
    - title: 'Contact'
      url: '/contact'

grid_settings:
  grid_spacing: 10

contact_settings:
  form_action: 'https://formspree.io/christoph@schorn.me'
  confirmation_url: '/thanks'
  email_subject: 'Contact form submission'
  send_button_text: 'Send Message'

social_settings:
  facebook_url: ''
  twitter_url: ''
  snapchat_url: ''
  youtube_url: ''
  google-plus_url: ''
  vimeo_url: ''
  pinterest_url: ''
  medium_url: ''
  quora_url: ''
  amazon_url: ''
  apple_url: ''
  android_url: ''
  tumblr_url: ''
  dribbble_url: ''
  behance_url: ''
  deviantart_url: ''
  email_url: 
    type: fas
    icon: at
    link: 'mailto'
  github_url: 'https://github.com/chrschorn'
  reddit_url: ''
  flickr_url: ''
  etsy_url: ''
  kickstarter_url: ''
  soundcloud_url: ''
  spotify_url: ''
  bandcamp_url: ''
  linkedin_url: 'https://www.linkedin.com/in/christoph-schorn'
  xing_url: 'https://xing.to/christoph-schorn'
  instagram_url: 'https://www.instagram.com/chrschrn'
  papers_url:
    type: fas
    icon: scroll
    link: 'https://scholar.google.de/citations?user=0PlA9CsAAAAJ'

color_settings:
  background_color: '#212121'
  background_alt_color: '#2c2c2c'
  text_dark_color: '#ffffff'
  text_medium_color: '#b7b7b7'
  text_light_color: '#6a6a6a'
  accent_color: '#0089ff'
  socials-color: '#4c4c4c'
  border_color: '#6c6c6c'
  overlay_background_color: '#161B21'
  overlay_text_color: '#ffffff'
  error_color: '#D64541'

font_settings:
  font_embed: '<link href="https://fonts.googleapis.com/css?family=Nunito+Sans|Open+Sans" rel="stylesheet">'
  title_font: "'Nunito Sans', sans-serif"
  body_font: "'Nunito Sans', sans-serif"
  regular_weight: 400
  bold_weight: 600
  site_title:
    small_size: 27
    medium_size: 32
    large_size: 40
    weight: 600
    letter_spacing: 0
  site_tagline:
    small_size: 16
    medium_size: 18
    large_size: 20
    weight: 400
    letter_spacing: 0
    line_height: 1.5
  menu:
    small_size: 20
    medium_size: 22
    large_size: 24
    weight: 100
    letter_spacing: 0
  h1:
    small_size: 27
    medium_size: 38
    large_size: 50
    weight: 600
    letter_spacing: -0.02
    line_height: 1.2
  h2:
    small_size: 27
    medium_size: 38
    large_size: 50
    weight: 600
    letter_spacing: -0.02
    line_height: 1.2
  h3:
    small_size: 22
    medium_size: 25
    large_size: 30
    weight: 400
    letter_spacing: -0.02
    line_height: 1.3
  h4:
    small_size: 17
    medium_size: 22
    large_size: 22
    weight: 400
    letter_spacing: 0
    line_height: 1.6
  h5:
    small_size: 17
    medium_size: 20
    large_size: 20
    weight: 400
    letter_spacing: 0
    line_height: 1.6
  h6:
    small_size: 17
    medium_size: 20
    large_size: 20
    weight: 400
    letter_spacing: 0
    line_height: 1.6
  p:
    small_size: 14
    medium_size: 16
    large_size: 19
    weight: 400
    letter_spacing: 0
    line_height: 1.6
  blockquote:
    small_size: 25
    medium_size: 35
    large_size: 45
    weight: 300
    letter_spacing: -0.02
    line_height: 1.6
  buttons:
    weight: 600
    letter_spacing: 0

advanced_settings:
  ajax_loading: true
  analytics_code: |
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-80555380-2"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-80555380-2');
    </script>
  custom_styles: ""
  header_js: ""
  footer_js: |
    <script>
      $(document).ready(function() {
        $loadins = $('[class*=loadin]').find('*');
        $loadins.addClass("animate");
        
        setTimeout(function() { $loadins.removeClass(function (index, css) {
          return (css.match (/\bloadin-\S+/g) || css.match (/\banimate-\S+/g) || []).join(' ');
        });}, 1400);

        var email = "christoph" + "@" + "schorn" + ".me";
        $("a.insertemail").html(email).attr('href', 'mailto:' + email);
        $("a[href='mailto']").attr('href', 'mailto:' + email);
      });
    </script>

    <script>
      var target = document.body;
      var execOnNextObservation = false;

      function observationCallback() {
          (function(){
          var i, e, d = document, s = "script";i = d.createElement("script");i.async = 1;
          i.src = "https://cdn.curator.io/published/cfadda0c-990f-4050-891b-f01c79e8a20b.js";
          e = d.getElementsByTagName(s)[0];e.parentNode.insertBefore(i, e);
          })();
      }

      var ob = new MutationObserver(function() {
          if (execOnNextObservation && !target.classList.contains("loading"))
          {
              observationCallback();
              execOnNextObservation = false;
          } else if (target.classList.contains("loading")) {
              execOnNextObservation = true;
          }
      });

      ob.observe(target, {
          attributes: true,
          attributeFilter: ["class"]
      });
    </script>